#
# Software Name : 5G-all-in-one-helm
# SPDX-FileCopyrightText: Copyright (c) 2022
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- if eq .Values.global.userPlaneArchitecture "single" }}
{{- with .Values.upf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.global.projectName }}
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration
    
    configuration:
      {{- $.Files.Get "configuration.yaml" | nindent 6 }}
    
      pfcp:
        - addr: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-0
    
      gtpu:
        - addr: {{ include "free5gc-upf.fullname" $ }}-{{ .name }}-0
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif
    
  wrapper.sh: |
    #!/bin/sh

    ### Implement networking rules
    iptables -A FORWARD -j ACCEPT
    iptables -t nat -A POSTROUTING -s {{ $.Values.global.uesubnet }} -o eth0 -j MASQUERADE  # route traffic comming from the UE SUBNET to the interface N6    
    echo "1200 n6if" >> /etc/iproute2/rt_tables # create a routing table for the interface N6
    ip rule add from {{ $.Values.global.uesubnet }} table n6if   # use the created ip table to route the traffic comming from the UE SUBNET 
    

    /free5gc/free5gc-upfd/free5gc-upfd -c {{ .volume.mount }}/upfcfg.yaml

{{- end }}
{{- end }}
