#
# Software Name : 5G-all-in-one-helm
# SPDX-FileCopyrightText: Copyright (c) 2022
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.n3iwf }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "free5gc-n3iwf.fullname" $ }}-{{ .name }}
  labels:
    {{- include "free5gc-n3iwf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  serviceName: {{ $.Values.global.n3iwf.service.n3.name }}
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "free5gc-n3iwf.selectorLabels" $ | nindent 6 }}
      project: {{ $.Values.global.projectName }}
      nf: {{ .name }}
  template:
    metadata:
      annotations:
        {{- include "free5gc-n3iwf.n3iwfAnnotations" $ | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/n3iwf-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "free5gc-n3iwf.selectorLabels" $ | nindent 8 }}
        project: {{ $.Values.global.projectName }}
        nf: {{ .name }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .name }}
        image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        imagePullPolicy: {{ .image.pullPolicy }}
        securityContext:
            {{- toYaml .securityContext | nindent 12 }}
        command: ["sh", "-c", "../config/n3iwf-ipsec.sh && ./n3iwf -c ../config/n3iwfcfg.yaml"]
        #command: ["sh", "-c", "../config/n3iwf-ipsec.sh && sleep 60000"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- if $.Values.global.n3iwf.nodeSelector }}
      nodeSelector: {{- $.Values.global.n3iwf.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        projected:
          sources:
          - configMap:
              name: {{ .configmap.name }}
              items:
              - key: n3iwfcfg.yaml
                path: n3iwfcfg.yaml
              - key: n3iwf-ipsec.sh
                path: n3iwf-ipsec.sh
                mode: 0777
{{- end }}