#
# Software Name : 5G-all-in-one-helm
# SPDX-FileCopyrightText: Copyright (c) 2022
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.smf }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  labels:
    {{- include "free5gc-smf.labels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "free5gc-smf.selectorLabels" $ | nindent 4 }}
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.global.smf.service.n4.name }}
  labels:
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
spec:
  type: {{ $.Values.global.smf.service.n4.type }}
  ports:
    - name: n4
      port: {{ $.Values.global.smf.service.n4.port }}
      targetPort: {{ $.Values.global.smf.service.n4.targetport }}
      protocol: {{ $.Values.global.smf.service.n4.protocol }}
  selector:
    project: {{ $.Values.global.projectName }}
    nf: {{ .name }}
{{- end }}
